### ISSUE TITLE
Configure difficulty?

### ISSUE THREAD

**Issue by qiqi-impact** [marwanhawari/LeetRooms#17]
Would be useful to have easier/harder distributions rather than the default Easy/Med/Med/Hard.

**Comment by marwanhawari** [comment]
https://github.com/marwanhawari/LeetRooms/pull/18 allows the user to select which difficulty of questions are allowed in the room.

If you choose all 3, it will try to do easy/med/med/hard. If you select 2 difficulties it will try to get an even split between them. If you choose just 1, it will give you only that difficulty. 

I considered allowing users to select the actual number of easy/med/hard, but I didn't like that user experience.
