### ISSUE TITLE
Make side panel resizable

### ISSUE THREAD

**Issue by marwanhawari** [marwanhawari/LeetRooms#2]
The right side panel for LeetRooms is currently a static width. Users should be able to resize like they resize the left side panel. This will involve making changes to the `content.ts` script rather than the React app. Ideally, it should look close in style and feel to the resizable element that already exists on the left side panel.

**Comment by marwanhawari** [comment]
This PR allows users to resize from the popup HTML:
- https://github.com/marwanhawari/LeetRooms/pull/6

It works, but it isn't the best UX. I would still like to allow users to drag to resize to match the existing LeetCode UI.

**Comment by rp111000** [comment]
Hi, I started working on this today. I was able to get most of the logic down. I'll clean up the code a bit and submit a PR soon.

This is what the current implementation looks like. Let me know if this works and if you would like me to add anything else.

[Resize](https://streamable.com/bj1bpf)

**Comment by marwanhawari** [comment]
I ended up merging my branch. Thanks for the contribution though.
