### ISSUE TITLE
Death mode rooms

### ISSUE THREAD

**Issue by smarttcoder** [marwanhawari/LeetRooms#25]
There are regular rooms and then there are death mode rooms. When death mode is activated, the user gets only 1 wrong submission or tle. The second submission must be accepted! If second submission also fails, they are “eliminated”, i.e their score till then is finalised and subsequent accepted submissions are not counted towards the score.

**Comment by marwanhawari** [comment]
Interesting concept, but closing this because it isn't quite within the scope of the project.
