### ISSUE TITLE
Re-add extension toggle to completely hide LeetRooms panel

### ISSUE THREAD

**Issue by qiqi-impact** [marwanhawari/LeetRooms#49]
Distracting to show the side panel thing when not in use (e.g. during a contest). Right now, I'm just disabling the extension while not in use.

Could still keep this mini-panel's functionality, just need an extension-level way to disable the entire UI.
![Screenshot 2023-06-21 175940](https://github.com/marwanhawari/LeetRooms/assets/102013397/d05cab4d-64f4-44ed-8245-b59aa0ae5f2b)

**Comment by marwanhawari** [comment]
Fair. I'll add back the extension-level toggle.

**Comment by marwanhawari** [comment]
Fixed in https://github.com/marwanhawari/LeetRooms/pull/63

**Comment by qiqi-impact** [comment]
ty!
