### ISSUE TITLE
[Bug] No direct button to hide the complete Panel

### ISSUE THREAD

**Issue by immortalcodes** [marwanhawari/LeetRooms#55]
![image](https://github.com/marwanhawari/LeetRooms/assets/92226302/e771ae3e-7f3e-4a46-8cd6-0e10b3bda232)

As could be seen in the image , there is no direct button to hide complete panel to focus completely on question , like in the image below one can click on the side bar to make leetroom appear.
![image](https://github.com/marwanhawari/LeetRooms/assets/92226302/629268b9-5e4e-4d93-8efd-c896d227e796)

**Comment by marwanhawari** [comment]
Fixed in https://github.com/marwanhawari/LeetRooms/pull/63
