### ISSUE TITLE
LeetRooms does not recognize submission result on leetcode's new Dynamic Layout

### ISSUE THREAD

**Issue by spacian** [marwanhawari/LeetRooms#58]
When I use the new Dynamic Layout on leetcode, LeetRooms won't update with the submission results.

I.e. I solve a problem in the current leetroom, hit submit and '\<user\> submitted' will appear in chat. However, on AC the text '\<user\> solved \<problem\>' won't appear and on theoretically solving the whole room, the final message (\<user\> solved room in \<x\> minutes or something) is also not shown.

I can switch back to Split View and the extension will work properly again. I have to resubmit all problems on Split View if I already submitted on the Dynamic Layout though.

**Comment by marwanhawari** [comment]
LeetCode is always going to be updating some part of their UI and the extension will be a little behind. Most recently, this was fixed by https://github.com/marwanhawari/LeetRooms/pull/61 and as of 4/11/24, the accepted submission detection is working again.
