### ISSUE TITLE
Leetroom panel not showing up in problem window at all

### ISSUE THREAD

**Issue by riyasunil** [marwanhawari/LeetRooms#59]
![image](https://github.com/marwanhawari/LeetRooms/assets/97850633/fea5bfd5-b54f-44b0-a5a9-dfa400f32016)
![image](https://github.com/marwanhawari/LeetRooms/assets/97850633/d5db3460-4e5f-4d28-837c-a7cc4baee477)

As shown in the attached images, the sidebar isnt showing up at all once you click on a question to get started.

after solving the problem and submitting it,  if you go back a page, no submission "thumbs up" is shown nor is the scoreboard filled.

**Comment by Maigiwag** [comment]
yea im having the same isssue currently i think leetrooms is temporarily broken...

**Comment by vimkim** [comment]
I'm hoping for this issue to be resolved. Appreciate the great work!

**Comment by TejasN09** [comment]
same here.................... :(

**Comment by Khanshujaath007** [comment]
Please fix it asap it's really helpful tool.

**Comment by vimkim** [comment]
It now works!!!!
