### ISSUE TITLE
Support for Firefox

### ISSUE THREAD

**Issue by SandroHc** [marwanhawari/LeetRooms#60]
Are there plans to publish this extension for Firefox?

**Comment by marwanhawari** [comment]
There are currently no plans to publish this for Firefox. The main reason is that Firefox disables 3rd party cookies by default, so users would have to go into their settings and enable 3rd party cookies on leetcode.com before they could get the extension to work. Also, I don't foresee myself being able to maintain LeetRooms on multiple browsers.
